name: ZAP Baseline DAST Scan

on: [push, pull_request]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build -t python-app -f Dockerfile .

      - name: Run the Docker container
        run: |
          docker run --rm -d -p 8000:8000 python-app
          sleep 10

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:8000"
          fail_action: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_json.json