name: ZAP Baseline DAST Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t python-app .

      - name: Run application container
        run: |
          docker run -d --name python-app-test -p 8000:8000 python-app
          sleep 15  # laisse le temps à l'app de démarrer

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://host.docker.internal:8000'
          fail_action: false
          artifact_name: zap-report

      - name: Stop and remove application container
        if: always()
        run: |
          docker stop python-app-test
          docker rm python-app-test
